### PR TITLE
README provides instructions on mounting OASis database through Docker

### PR DESCRIPTION
**Pull request by erikr**
Will remove my revised `docker-compose.yml` after confirming success.

### CODE REVIEW

**Comment by prihoda** [comment]
Hi @erikr, thanks for looking into this. Can you check if it's possible to define the mount directory as a commandline argument to docker compose, instead of specifying it in the docker compose file? So that people wouldn't have to modify the code to run the application.

**Comment by erikr** [comment]
Agreed it would be cleaner to run the app without modifying code and instead adding an argument. However, does not appear that `docker-compose up` supports this: https://docs.docker.com/compose/reference/up/

**Comment by prihoda** [comment]
Seems like an `.env` file might work: https://docs.docker.com/compose/environment-variables/

The `.env` file could be ignored using `.gitignore`

**Comment by prihoda** [comment]
so the db could be set fixed to `OASIS_DB_PATH=/mnt/data/OASis_9mers_v1.db` and the volume would be parametrized:
```
volumes:
      - ${DATA_DIR:-./data/}:/mnt/data
```

Then `./data/` would be used as default DATA_DIR. If using such a local directory, we should also add a `.dockerignore` file containing `./data`, so that the directory is not copied to the docker image when building. 

Then the user could also create their own `.env` file changing `DATA_DIR`

**Pull request closed without merging**
